### ISSUE TITLE
Remove csvreader_kwargs from AeronetSunTimeseriesReader

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaro-readers#15]
The AeronetSunTimeseriesReader has a csvreader_kwargs argument. This parameter should be removed and the delimiter hard-coded, since I doubt that it really should be user defined for the Aeronet data.

```python
class AeronetSunTimeseriesReader(AutoFilterReaderEngine.AutoFilterReader):
    def __init__(
        self,
        filename,
        csvreader_kwargs={"delimiter": DELIMITER},
```

**Comment by jgriesfeller** [comment]
that is actually right
