### ISSUE TITLE
adjust to pyaro's updated filter init

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaro-readers#23]
instead of https://github.com/metno/pyaro-readers/blob/22ca00ae1bc564a927b9fc757d31c44ffca355ad/src/pyaro_readers/aeronetsdareader/AeronetSdaTimeseriesReader.py#L101
and 
https://github.com/metno/pyaro-readers/blob/22ca00ae1bc564a927b9fc757d31c44ffca355ad/src/pyaro_readers/aeronetsunreader/AeronetSunTimeseriesReader.py#L90

use 
```python
self._set_filters(filters)
```

**Comment by dulte** [comment]
PR #24

**Comment by jgriesfeller** [comment]
merged
