### ISSUE TITLE
CSV test data missing

### ISSUE THREAD

**Issue by dulte** [metno/pyaro-readers#30]
When using the url for the test data, it returns the readthedocs page instead

**Comment by heikoklein** [comment]
@dulte Is this about the CSV-reader? The CSV-reader comes bundled with pyaro and is not part of pyaro-readers. Can you in that case move the issue to pyaro?

**Comment by dulte** [comment]
@heikoklein No, it's about the csv test data for the aeronet reader. `https://pyaerocom.met.no/pyaro-suppl/testdata/aeronetsun_testdata.csv`


 But I talked with Jan some weeks ago, and I think it had to do with the with some routing on the server, which you fixed. I will check and make sure that the test data is working now, and in that case close the issue.

**Comment by heikoklein** [comment]
Just for your information: pyaerocom-ng.met.no  (-ng = next generation) has now been disabled. (Was planned as temporary site, but somebody put links from the tests to those pages. Should be fixed by now.)
