### ISSUE TITLE
Add a EEA Reader supporting the new parquet based format

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaro-readers#43]
pyaerocom read EEA data currently still through a reader of it's own, which uses huge amount of memory and long processing time. In addition, the current EEA dataformat will be discontinued by the end of the year and replaced by a parquet based format.
A pyaro-reader for the new EEA data-format needs to be implemented. During the implementation it should be decided if the new format is efficient enough or should be converted to another format (e.g. netcdf-rw of pyaro-reader).

**Comment by jgriesfeller** [comment]
the current EEA data format will be discontinued at the end of the year (read https://discomap.eea.europa.eu/map/fme/AirQualityExport.htm).
New API is here:
https://eeadmz1-downloads-webapp.azurewebsites.net/
and uses Parqet files as format.
So I guess we don't do any further development here?

**Comment by heikoklein** [comment]
Thanks for checking the documentation.
Doesn't this make this issue even more relevant in that we need a new EEA reader because the old one is soon to be discontinued? I will reformulate the issue slightly, but keep it.
